import { TemplateType } from '@/contexts/TemplateContext';

export interface TemplateStyles {
  // Layout
  containerPadding: { xs: number; md: number };
  sectionSpacing: number;
  cardPadding: { xs: number; md: number };
  cardBorderRadius: number;
  cardShadow: string;
  
  // Typography
  headingFontSize: { xs: string; md: string };
  headingLetterSpacing: string;
  headingTransform: 'uppercase' | 'none' | 'capitalize';
  bodyFontSize: { xs: string; md: string };
  bodyLineHeight: number;
  
  // Colors & Effects
  cardBackground: string;
  cardBorder: string;
  accentLineWidth: string;
  accentLineHeight: string;
  hoverEffect: string;
  
  // Header
  headerStyle: 'minimal' | 'bold' | 'decorative' | 'artistic';
  headerPadding: { xs: number; md: number };
  
  // Cards
  cardStyle: 'flat' | 'elevated' | 'bordered' | 'gradient';
  cardGap: number;
  
  // Sections
  sectionBackground: 'transparent' | 'alternating' | 'solid';
}

export const templateStyles: Record<TemplateType, TemplateStyles> = {
  compact: {
    containerPadding: { xs: 2, md: 3 },
    sectionSpacing: 3,
    cardPadding: { xs: 2.5, md: 3 },
    cardBorderRadius: 0,
    cardShadow: 'none',
    headingFontSize: { xs: '1rem', md: '1.125rem' },
    headingLetterSpacing: '0.03em',
    headingTransform: 'uppercase',
    bodyFontSize: { xs: '0.875rem', md: '0.9375rem' },
    bodyLineHeight: 1.6,
    cardBackground: 'white',
    cardBorder: '1px solid #e5e7eb',
    accentLineWidth: '40px',
    accentLineHeight: '2px',
    hoverEffect: 'translateY(-2px)',
    headerStyle: 'minimal',
    headerPadding: { xs: 4, md: 5 },
    cardStyle: 'bordered',
    cardGap: 2,
    sectionBackground: 'transparent',
  },
  elegant: {
    containerPadding: { xs: 4, md: 6 },
    sectionSpacing: 4,
    cardPadding: { xs: 4, md: 5 },
    cardBorderRadius: 2,
    cardShadow: '0 2px 8px rgba(0,0,0,0.08), 0 4px 16px rgba(0,0,0,0.04)',
    headingFontSize: { xs: '1.25rem', md: '1.5rem' },
    headingLetterSpacing: '0.05em',
    headingTransform: 'uppercase',
    bodyFontSize: { xs: '0.9375rem', md: '1rem' },
    bodyLineHeight: 1.9,
    cardBackground: 'white',
    cardBorder: '1px solid rgba(0,0,0,0.06)',
    accentLineWidth: '60px',
    accentLineHeight: '3px',
    hoverEffect: 'translateY(-4px)',
    headerStyle: 'decorative',
    headerPadding: { xs: 6, md: 8 },
    cardStyle: 'elevated',
    cardGap: 4,
    sectionBackground: 'alternating',
  },
  modern: {
    containerPadding: { xs: 3, md: 4 },
    sectionSpacing: 5,
    cardPadding: { xs: 3.5, md: 4.5 },
    cardBorderRadius: 3,
    cardShadow: '0 4px 20px rgba(0,0,0,0.1)',
    headingFontSize: { xs: '1.375rem', md: '1.75rem' },
    headingLetterSpacing: '0.02em',
    headingTransform: 'none',
    bodyFontSize: { xs: '1rem', md: '1.0625rem' },
    bodyLineHeight: 1.8,
    cardBackground: 'white',
    cardBorder: 'none',
    accentLineWidth: '80px',
    accentLineHeight: '4px',
    hoverEffect: 'translateY(-6px) scale(1.02)',
    headerStyle: 'bold',
    headerPadding: { xs: 7, md: 10 },
    cardStyle: 'elevated',
    cardGap: 5,
    sectionBackground: 'alternating',
  },
  creative: {
    containerPadding: { xs: 3, md: 5 },
    sectionSpacing: 6,
    cardPadding: { xs: 4, md: 6 },
    cardBorderRadius: 4,
    cardShadow: '0 8px 32px rgba(0,0,0,0.12)',
    headingFontSize: { xs: '1.5rem', md: '2rem' },
    headingLetterSpacing: '0.01em',
    headingTransform: 'capitalize',
    bodyFontSize: { xs: '1rem', md: '1.125rem' },
    bodyLineHeight: 2,
    cardBackground: 'linear-gradient(135deg, #ffffff 0%, #f9fafb 100%)',
    cardBorder: '2px solid transparent',
    accentLineWidth: '100px',
    accentLineHeight: '5px',
    hoverEffect: 'translateY(-8px) scale(1.03) rotate(0.5deg)',
    headerStyle: 'artistic',
    headerPadding: { xs: 8, md: 12 },
    cardStyle: 'gradient',
    cardGap: 6,
    sectionBackground: 'solid',
  },
  classic: {
    containerPadding: { xs: 3, md: 4 },
    sectionSpacing: 4,
    cardPadding: { xs: 3, md: 4 },
    cardBorderRadius: 0,
    cardShadow: 'none',
    headingFontSize: { xs: '1.125rem', md: '1.25rem' },
    headingLetterSpacing: '0.05em',
    headingTransform: 'uppercase',
    bodyFontSize: { xs: '0.9375rem', md: '1rem' },
    bodyLineHeight: 1.7,
    cardBackground: 'white',
    cardBorder: '1px solid #d1d5db',
    accentLineWidth: '50px',
    accentLineHeight: '2px',
    hoverEffect: 'none',
    headerStyle: 'minimal',
    headerPadding: { xs: 5, md: 6 },
    cardStyle: 'bordered',
    cardGap: 3,
    sectionBackground: 'transparent',
  },
  contemporary: {
    containerPadding: { xs: 3, md: 5 },
    sectionSpacing: 5,
    cardPadding: { xs: 3.5, md: 4.5 },
    cardBorderRadius: 2,
    cardShadow: '0 3px 12px rgba(0,0,0,0.1)',
    headingFontSize: { xs: '1.25rem', md: '1.5rem' },
    headingLetterSpacing: '0.03em',
    headingTransform: 'uppercase',
    bodyFontSize: { xs: '0.9375rem', md: '1rem' },
    bodyLineHeight: 1.75,
    cardBackground: 'white',
    cardBorder: '2px solid #e5e7eb',
    accentLineWidth: '70px',
    accentLineHeight: '3px',
    hoverEffect: 'translateY(-3px)',
    headerStyle: 'bold',
    headerPadding: { xs: 6, md: 8 },
    cardStyle: 'elevated',
    cardGap: 4,
    sectionBackground: 'alternating',
  },
  timeline: {
    containerPadding: { xs: 3, md: 4 },
    sectionSpacing: 4,
    cardPadding: { xs: 3, md: 4 },
    cardBorderRadius: 0,
    cardShadow: 'none',
    headingFontSize: { xs: '1.125rem', md: '1.375rem' },
    headingLetterSpacing: '0.02em',
    headingTransform: 'none',
    bodyFontSize: { xs: '0.9375rem', md: '1rem' },
    bodyLineHeight: 1.8,
    cardBackground: 'white',
    cardBorder: 'none',
    accentLineWidth: '60px',
    accentLineHeight: '3px',
    hoverEffect: 'translateY(-2px)',
    headerStyle: 'minimal',
    headerPadding: { xs: 5, md: 7 },
    cardStyle: 'flat',
    cardGap: 3,
    sectionBackground: 'transparent',
  },
  stylish: {
    containerPadding: { xs: 2, md: 3 },
    sectionSpacing: 3,
    cardPadding: { xs: 2.5, md: 3.5 },
    cardBorderRadius: 1,
    cardShadow: '0 2px 6px rgba(0,0,0,0.08)',
    headingFontSize: { xs: '1rem', md: '1.125rem' },
    headingLetterSpacing: '0.04em',
    headingTransform: 'uppercase',
    bodyFontSize: { xs: '0.875rem', md: '0.9375rem' },
    bodyLineHeight: 1.65,
    cardBackground: 'white',
    cardBorder: '1px solid #e5e7eb',
    accentLineWidth: '45px',
    accentLineHeight: '2px',
    hoverEffect: 'translateY(-2px)',
    headerStyle: 'minimal',
    headerPadding: { xs: 4, md: 5 },
    cardStyle: 'bordered',
    cardGap: 2.5,
    sectionBackground: 'transparent',
  },
  polished: {
    containerPadding: { xs: 4, md: 6 },
    sectionSpacing: 5,
    cardPadding: { xs: 4, md: 5.5 },
    cardBorderRadius: 2.5,
    cardShadow: '0 4px 16px rgba(0,0,0,0.1), 0 8px 24px rgba(0,0,0,0.06)',
    headingFontSize: { xs: '1.25rem', md: '1.5rem' },
    headingLetterSpacing: '0.04em',
    headingTransform: 'uppercase',
    bodyFontSize: { xs: '0.9375rem', md: '1rem' },
    bodyLineHeight: 1.85,
    cardBackground: 'white',
    cardBorder: '1px solid rgba(0,0,0,0.08)',
    accentLineWidth: '65px',
    accentLineHeight: '3px',
    hoverEffect: 'translateY(-5px)',
    headerStyle: 'decorative',
    headerPadding: { xs: 6, md: 9 },
    cardStyle: 'elevated',
    cardGap: 4.5,
    sectionBackground: 'alternating',
  },
  'ivy-league': {
    containerPadding: { xs: 4, md: 5 },
    sectionSpacing: 4,
    cardPadding: { xs: 3.5, md: 4.5 },
    cardBorderRadius: 0,
    cardShadow: 'none',
    headingFontSize: { xs: '1.125rem', md: '1.25rem' },
    headingLetterSpacing: '0.06em',
    headingTransform: 'uppercase',
    bodyFontSize: { xs: '0.9375rem', md: '1rem' },
    bodyLineHeight: 1.75,
    cardBackground: 'white',
    cardBorder: '1px solid #e5e7eb',
    accentLineWidth: '55px',
    accentLineHeight: '2px',
    hoverEffect: 'none',
    headerStyle: 'minimal',
    headerPadding: { xs: 5, md: 7 },
    cardStyle: 'bordered',
    cardGap: 3.5,
    sectionBackground: 'transparent',
  },
  'double-column': {
    containerPadding: { xs: 2, md: 3 },
    sectionSpacing: 3,
    cardPadding: { xs: 2.5, md: 3 },
    cardBorderRadius: 1,
    cardShadow: '0 2px 8px rgba(0,0,0,0.08)',
    headingFontSize: { xs: '1rem', md: '1.125rem' },
    headingLetterSpacing: '0.03em',
    headingTransform: 'uppercase',
    bodyFontSize: { xs: '0.875rem', md: '0.9375rem' },
    bodyLineHeight: 1.7,
    cardBackground: 'white',
    cardBorder: '1px solid #e5e7eb',
    accentLineWidth: '50px',
    accentLineHeight: '2px',
    hoverEffect: 'translateY(-2px)',
    headerStyle: 'decorative',
    headerPadding: { xs: 4, md: 6 },
    cardStyle: 'bordered',
    cardGap: 2.5,
    sectionBackground: 'transparent',
  },
  'high-performer': {
    containerPadding: { xs: 3, md: 4 },
    sectionSpacing: 4,
    cardPadding: { xs: 3, md: 4 },
    cardBorderRadius: 1.5,
    cardShadow: '0 3px 10px rgba(0,0,0,0.09)',
    headingFontSize: { xs: '1.125rem', md: '1.375rem' },
    headingLetterSpacing: '0.03em',
    headingTransform: 'uppercase',
    bodyFontSize: { xs: '0.9375rem', md: '1rem' },
    bodyLineHeight: 1.75,
    cardBackground: 'white',
    cardBorder: '1px solid #e5e7eb',
    accentLineWidth: '60px',
    accentLineHeight: '3px',
    hoverEffect: 'translateY(-3px)',
    headerStyle: 'bold',
    headerPadding: { xs: 5, md: 7 },
    cardStyle: 'elevated',
    cardGap: 3.5,
    sectionBackground: 'alternating',
  },
};

